# SITE CONFIGURATION
baseurl: ""
url: "https://blogs.roshanparajuli.com.np"

# THEME-SPECIFIC CONFIGURATION
title: Blogs # site's title
description: "Pouring my research on my blogs." # used by search engines
avatar: assets/img/logo.png # Empty for no avatar in navbar
favicon: assets/img/logo.png # Icon displayed in the tab

# Header and footer text
header_text: Change <code>header_text</code> in <code>_config.yml</code> # Change Blog header text
header_feature_image: assets/img/header.png
footer_text: >
  Author: <a href="https://roshanparajuli.com.np/">Roshan Parajuli</a>

# Blog
excerpt: true # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png # A bit transparent for color posts.

# Features
# More in the _data folder for share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true # Enable if using math markup
mermaid: true # Enable mermaid-js for sequence and diagrams
google_analytics: # Tracking ID, e.g. "UA-000000-01"
cookie_consent: false # To respect the usage of cookies
color_theme: auto # auto, dark or light

repository: rsnpj/blog

# comments:
# disqus_shortname:                                     # Your discus shortname for comments
cusdis_app_id: 9c12daad-69de-4ef4-bc6a-2c733df8a320 # Your cusdis data-app-id
# utterances:                                           # Enable by filling below information. For more info, go to https://utteranc.es
#   repo:                                               # your public comments repository (e.g. owner/repo)
#   issue-term:                                         # Issue term (e.g. "comment" consider issues with this word in the title as comments)

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
sass:
  style: compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", ".idea", "vendor/*", "assets/node_modules/*"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap # If using as a remote_theme in github
